package com.schwisolutions.librarymanagement.repository

import com.schwisolutions.librarymanagement.data.dao.BookDao
import com.schwisolutions.librarymanagement.data.entity.Book
import kotlinx.coroutines.flow.Flow

/**
 * Concrete implementation of BookRepository delegating operations to Room's BookDao.
 *
 * Official docs reference:
 * - developer.android.com/topic/architecture/data-layer#repository
 *
 * @param bookDao Data access object generated by Room compiler.
 */
class OfflineBookRepository(private val bookDao: BookDao) : BookRepository {

    override fun getAllBooksStream(): Flow<List<Book>> {
        return bookDao.getAllBooks()
    }

    override fun getBookStream(id: Int): Flow<Book?> {
        return bookDao.getBookById(id)
    }

    override fun searchBooksStream(query: String): Flow<List<Book>> {
        return bookDao.searchBooks(query)
    }

    override suspend fun insertBook(book: Book) {
        bookDao.insertBook(book)
    }

    override suspend fun updateBook(book: Book) {
        bookDao.updateBook(book)
    }

    override suspend fun deleteBook(book: Book) {
        bookDao.deleteBook(book)
    }
}
